<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>injectionSelector</key>
	<string>string.quoted.single.html,string.quoted.double.html</string>
	<key>name</key>
	<string>Kit Variable</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(&lt;!--)(\s*)(\$[a-zA-Z][a-zA-Z0-9_-]+\?*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.html.kit</string>
				</dict>
				<key>3</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#import</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#opt-variable</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#variable</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>end</key>
			<string>(--&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.html.kit</string>
				</dict>
			</dict>
			<key>name</key>
			<string>comment.block.kit</string>
			<key>patterns</key>
			<array>
				<dict/>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>opt-variable</key>
		<dict>
			<key>match</key>
			<string>[\$,\@][a-zA-Z][a-zA-Z0-9_-]+\?</string>
			<key>name</key>
			<string>variable.other.optional.kit</string>
		</dict>
		<key>variable</key>
		<dict>
			<key>match</key>
			<string>[\$,\@][a-zA-Z][a-zA-Z0-9_-]+</string>
			<key>name</key>
			<string>variable.other.kit</string>
		</dict>
	</dict>
	<key>uuid</key>
	<string>FE19391F-D503-4AF2-9EF9-9E68E4E5E5F8</string>
</dict>
</plist>
