<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>kit</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~K</string>
	<key>name</key>
	<string>Kit</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(&lt;!--)(\s*)([\$,\@][a-zA-Z][a-zA-Z0-9_-]+\?*)(\s*)([\:\=]*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.html.kit</string>
				</dict>
				<key>3</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#import</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#opt-variable</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#variable</string>
						</dict>
					</array>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.assign</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(--&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.html.kit</string>
				</dict>
			</dict>
			<key>name</key>
			<string>comment.block.kit</string>
			<key>patterns</key>
			<array>
				<dict/>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>import</key>
		<dict>
			<key>match</key>
			<string>\@import</string>
			<key>name</key>
			<string>keyword.control.import.kit</string>
		</dict>
		<key>opt-variable</key>
		<dict>
			<key>match</key>
			<string>[\$,\@][a-zA-Z][a-zA-Z0-9_-]+\?</string>
			<key>name</key>
			<string>variable.other.optional.kit</string>
		</dict>
		<key>variable</key>
		<dict>
			<key>match</key>
			<string>[\$,\@][a-zA-Z][a-zA-Z0-9_-]+</string>
			<key>name</key>
			<string>variable.other.kit</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.html.kit</string>
	<key>uuid</key>
	<string>415CCD02-3BAE-4C8C-B082-3DC316E12CCA</string>
</dict>
</plist>
